// Generated by CoffeeScript 1.3.1
(function() {
  var hidePopUp, showArtwork, showMap, showPopUp, socket;

  socket = io.connect('http://localhost');

  showArtwork = function($scope) {
    $scope.showMap = false;
    $scope.showPopUp = false;
    return $scope.showArtwork = true;
  };

  showMap = function($scope) {
    $scope.showMap = true;
    $scope.showPopUp = false;
    return $scope.showArtwork = false;
  };

  showPopUp = function($scope) {
    return $scope.showPopUp = true;
  };

  hidePopUp = function($scope) {
    return $scope.showPopUp = false;
  };

  this.IndexCtrl = function($scope) {
    showMap($scope);
    $scope.availableLocations = [];
    socket.on('inProximity', function(data) {
      if (data.locations.length === 1) {
        if (!($scope.location != null)) {
          $scope.location = data.locations[0];
          showArtwork($scope);
        } else if ($scope.location !== data.locations[0]) {
          showPopUp($scope);
        }
      } else if (data.locations.length === 0 && !($scope.location != null)) {
        showMap($scope);
      } else if (data.locations.length === 2) {
        showPopUp($scope);
      }
      $scope.availableLocations = data.locations;
      return $scope.$apply();
    });
    $scope.selectLocation = function(location) {
      $scope.location = location;
      return showArtwork($scope);
    };
    return $scope.closeLocation = function() {
      $scope.location = null;
      return showMap($scope);
    };
  };

  this.ArtworkController = function($scope) {};

  this.MapController = function($scope) {};

  this.PopUpController = function($scope) {};

}).call(this);
